<?php

namespace App\Services;

use App\Models\AutomationRuleModel;
use App\Models\AutomationLogModel;

class AutomationService
{
    protected $ruleModel;
    protected $logModel;

    public function __construct()
    {
        $this->ruleModel = new AutomationRuleModel();
        $this->logModel  = new AutomationLogModel();
    }

    /**
     * Trigger automations for a specific object and event
     */
    public function trigger(string $object, string $event, array $data, int $tenantId)
    {
        $rules = $this->ruleModel->getActiveRules($tenantId, $event, $object);

        foreach ($rules as $rule) {
            if ($this->evaluateConditions($rule, $data)) {
                $this->executeAction($rule, $data, $tenantId);
            }
        }
    }

    /**
     * Simple condition evaluator (can be expanded)
     */
    protected function evaluateConditions(array $rule, array $data): bool
    {
        if (empty($rule['conditions'])) return true;

        $conditions = json_decode($rule['conditions'], true);
        if (!$conditions) return true;

        foreach ($conditions as $condition) {
            $field    = $condition['field'] ?? '';
            $operator = $condition['operator'] ?? '==';
            $value    = $condition['value'] ?? '';

            $actualValue = $data[$field] ?? null;

            switch ($operator) {
                case '==': if ($actualValue != $value) return false; break;
                case '!=': if ($actualValue == $value) return false; break;
                case '>':  if ($actualValue <= $value) return false; break;
                case '<':  if ($actualValue >= $value) return false; break;
                case 'contains': if (strpos((string)$actualValue, (string)$value) === false) return false; break;
            }
        }

        return true;
    }

    /**
     * Execute the defined action
     */
    protected function executeAction(array $rule, array $data, int $tenantId)
    {
        $actionType   = $rule['action_type'];
        $actionConfig = json_decode($rule['action_config'], true);
        $status       = 'success';
        $message      = 'Executed successfully';

        try {
            switch ($actionType) {
                case 'update_field':
                    $this->handleUpdateField($rule, $data, $actionConfig);
                    break;
                case 'create_task':
                    $this->handleCreateTask($rule, $data, $actionConfig, $tenantId);
                    break;
                // Add more actions here (send_email, etc.)
            }
        } catch (\Exception $e) {
            $status  = 'failed';
            $message = $e->getMessage();
        }

        // Log the execution
        $this->logModel->insert([
            'tenant_id'   => $tenantId,
            'rule_id'     => $rule['id'],
            'entity_id'   => $data['id'] ?? null,
            'status'      => $status,
            'message'     => $message,
            'executed_at' => date('Y-m-d H:i:s')
        ]);
    }

    protected function handleUpdateField(array $rule, array $data, array $config)
    {
        $db = \Config\Database::connect();
        $table = $rule['trigger_object'];
        $field = $config['field'] ?? '';
        $value = $config['value'] ?? '';

        if ($table && $field && isset($data['id'])) {
            $db->table($table)->where('id', $data['id'])->update([$field => $value]);
        }
    }

    protected function handleCreateTask(array $rule, array $data, array $config, int $tenantId)
    {
        $taskModel = new \App\Models\TaskModel();
        $projectId = $data['project_id'] ?? ($rule['trigger_object'] === 'projects' ? $data['id'] : null);

        if (!$projectId) return;

        $taskModel->insert([
            'tenant_id'   => $tenantId,
            'project_id'  => $projectId,
            'title'       => $config['title'] ?? 'Automated Task',
            'description' => $config['description'] ?? 'Generated by alert: ' . $rule['name'],
            'status'      => 'todo',
            'priority'    => 'medium',
            'created_by'  => 0 // 0 for System
        ]);
    }
}
